[package]
name = "AoC2020-Solutions"
version = "0.1.0"
authors = ["f0cus3d"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
